import random


# 1189 chapters
bible = {
        'genesis': {'chapters': 50, 'next': 'exodus'},
        'exodus': {'chapters': 40, 'next': 'leviticus'},
        'leviticus': {'chapters': 27, 'next': 'numbers'},
        'numbers': {'chapters': 36, 'next': 'deuteronomy'},
        'deuteronomy': {'chapters': 34, 'next': 'joshua'},
        'joshua': {'chapters': 24, 'next': 'judges'},
        'judges': {'chapters': 21, 'next': 'ruth'},
        'ruth': {'chapters': 4, 'next': '1 samuel'},
        '1 samuel': {'chapters': 31, 'next': '2 samuel'},
        '2 samuel': {'chapters': 24, 'next': '1 kings'},
        '1 kings': {'chapters': 22, 'next': '2 kings'},
        '2 kings': {'chapters': 25, 'next': '1 chronicles'},
        '1 chronicles': {'chapters': 29, 'next': '2 chronicles'},
        '2 chronicles': {'chapters': 36, 'next': 'ezra'},
        'ezra': {'chapters': 10, 'next': 'nehemiah'},
        'nehemiah': {'chapters': 13, 'next': 'esther'},
        'esther': {'chapters': 10, 'next': 'job'},
        'job': {'chapters': 42, 'next': 'psalms'},
        'psalms': {'chapters': 150, 'next': 'proverbs'},
        'proverbs': {'chapters': 31, 'next': 'ecclesiastes'},
        'ecclesiastes': {'chapters': 12, 'next': 'song of solomon'},
        'song of solomon': {'chapters': 8, 'next': 'isaiah'},
        'isaiah': {'chapters': 66, 'next': 'jeremiah'},
        'jeremiah': {'chapters': 52, 'next': 'lamentations'},
        'lamentations': {'chapters': 5, 'next': 'ezekiel'},
        'ezekiel': {'chapters': 48, 'next': 'daniel'},
        'daniel': {'chapters': 12, 'next': 'hosea'},
        'hosea': {'chapters': 14, 'next': 'joel'},
        'joel': {'chapters': 3, 'next': 'amos'},
        'amos': {'chapters': 9, 'next': 'obadiah'},
        'obadiah': {'chapters': 1, 'next': 'jonah'},
        'jonah': {'chapters': 4, 'next': 'micah'},
        'micah': {'chapters': 7, 'next': 'nahum'},
        'nahum': {'chapters': 3, 'next': 'habakkuk'},
        'habakkuk': {'chapters': 3, 'next': 'zephaniah'},
        'zephaniah': {'chapters': 3, 'next': 'haggai'},
        'haggai': {'chapters': 2, 'next': 'zechariah'},
        'zechariah': {'chapters': 14, 'next': 'malachi'},
        'malachi': {'chapters': 4, 'next': 'matthew'},
        'matthew': {'chapters': 28, 'next': 'mark'},
        'mark': {'chapters': 16, 'next': 'luke'},
        'luke': {'chapters': 24, 'next': 'john'},
        'john': {'chapters': 21, 'next': 'acts'},
        'acts': {'chapters': 28, 'next': 'romans'},
        'romans': {'chapters': 16, 'next': '1 corinthians'},
        '1 corinthians': {'chapters': 16, 'next': '2 corinthians'},
        '2 corinthians': {'chapters': 13, 'next': 'galatians'},
        'galatians': {'chapters': 6, 'next': 'ephesians'},
        'ephesians': {'chapters': 6, 'next': 'philippians'},
        'philippians': {'chapters': 4, 'next': 'colossians'},
        'colossians': {'chapters': 4, 'next': '1 thessalonians'},
        '1 thessalonians': {'chapters': 5, 'next': '2 thessalonians'},
        '2 thessalonians': {'chapters': 3, 'next': '1 timothy'},
        '1 timothy': {'chapters': 6, 'next': '2 timothy'},
        '2 timothy': {'chapters': 4, 'next': 'titus'},
        'titus': {'chapters': 3, 'next': 'philemon'},
        'philemon': {'chapters': 1, 'next': 'hebrews'},
        'hebrews': {'chapters': 13, 'next': 'james'},
        'james': {'chapters': 5, 'next': '1 peter'},
        '1 peter': {'chapters': 5, 'next': '2 peter'},
        '2 peter': {'chapters': 3, 'next': '1 john'},
        '1 john': {'chapters': 5, 'next': '2 john'},
        '2 john': {'chapters': 1, 'next': '3 john'},
        '3 john': {'chapters': 1, 'next': 'jude'},
        'jude': {'chapters': 1, 'next': 'revelation'},
        'revelation': {'chapters': 22, 'next': 'done'},
        'done': {'chapters': 0, 'next': 'done'}
}

def getRandomVerse():
        verses = [
                "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.\nAnd the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. \n\nPhilippians 4:6-7",
                'But above all, my brothers, do not swear, either by heaven or by earth or by any other oath, but let your “yes” be yes and your “no” be no, so that you may not fall under condemnation \n\nJames 5:12'
        ]
        return random.choice(verses)
